
spring:
  datasource:
    potgresql:
      url: jdbc:postgresql://localhost:5432/mytest
      username: postgres
      password: 111111
      driver-class-name: org.postgresql.Driver
    mysql:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 111111
      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:mapper/postgresql/*.xml
#  type-aliases-package: com.example.postgis_spring.module